```{r bar, cache=cacheon}

propfunc <- function(var, val = "Yes", name, data) {
  outprop <- data %>%
    filter(!is.na(!!sym(var))) %>%
    group_by(data) %>%
    count(!!sym(var)) %>%
    mutate(prop = n / sum(n) * 100) %>%
    ungroup() %>%
    filter(!!sym(var) == val) %>%
    select(-n, -!!sym(var), -data) %>%
    as.data.frame()

  rownames(outprop) <- levels(data3$data)

  colnames(outprop) <- name

  return(outprop)
}

propfunc2 <- function(data2) {
  prop <- propfunc(var = "sex", val = "Female", name = "Female", data2)
  prop <- cbind(
    prop,
    propfunc("age_cat", val = ">=75", "Age \u226575, years", data2)
  )
  prop <- cbind(
    prop,
    propfunc("mi", val = "Yes", "MI", data2)
  )
  prop <- cbind(
    prop,
    propfunc("diabetes", val = "Yes", "Diabetes", data2)
  )
  prop <- cbind(
    prop,
    propfunc("ckd", val = "Yes", "CKD", data2)
  )
  prop <- cbind(
    prop,
    propfunc("ef_cat39", val = "<30", "EF <30, %", data2)
  )
  prop <- cbind(
    prop,
    propfunc("hypertension", val = "Yes", "HT", data2)
  )
  prop <- cbind(
    prop,
    propfunc(var = "nyha_cat", val = "I-II", "NYHA I-II", data2)
  )
  prop <- cbind(
    prop,
    propfunc("rasarni", val = "Yes", "RASi", data2)
  )
  prop <- cbind(
    prop,
    propfunc("bbl", val = "Yes", "Betablockers", data2)
  )
  prop <- cbind(
    prop,
    propfunc("mra", val = "Yes", "MRA", data2)
  )
}
```

```{r barcrtind, cache=cacheon, fig.cap="Key baseline parameters for patients with CRT in CRT Survey II and indication for CRT in ESC and Swede HF. * are patients with CRT", dependson="bar", fig.height=6, fig.width=8}

crtgroup <- propfunc2(data3 %>% filter(crt == "CRT"))
indcrtgroup <- propfunc2(data3 %>% filter(data == "crt" | crt == "Indication"))

par(mar = c(6.7, 4.1, 0.5, 0.1))
#  bottom, left, top and right
b <- barplot(as.matrix(indcrtgroup),
  beside = T, col = global_cols[c(7, 4, 1)], ylim = c(0, 100),
  ylab = "Percent",
  axes = FALSE,
  names.arg = rep(NA, 11),
  border = NA
)
axis(2, seq(0, 100, 10), las = 2)
axis(1, b[2, ], names(indcrtgroup), las = 2, tick = F)

for (i in seq_along(names(indcrtgroup))) {
  points(c(b[2, i]), crtgroup["esc", i], pch = 8)
}
for (i in seq_along(names(indcrtgroup))) {
  points(c(b[3, i]), crtgroup["rs", i], pch = 8)
}

legend(
  "topleft",
  legend = c("ESC-CRT survey II", "ESC-HF-LT", "SwedeHF"),
  bty = "n",
  fill = global_cols[c(7, 4, 1)],
  border = NA
)
```

```{r barcrtindcomb, cache=cacheon, fig.cap="Key baseline parameters for patients with CRT in CRT Survey II and CRT/indication for CRT in ESC and Swede HF", dependson="bar", fig.height=6, fig.width=8}

group <- propfunc2(data2 = data3 %>% filter(crt %in% c("CRT", "Indication")))

par(mar = c(6.7, 4.1, 0.5, 0.1))
#  bottom, left, top and right
b <- barplot(as.matrix(group),
  beside = T, col = global_cols[c(7, 4, 1)], ylim = c(0, 100),
  ylab = "Percent",
  axes = FALSE,
  names.arg = rep(NA, 11),
  border = NA
)
axis(2, seq(0, 100, 10), las = 2)
axis(1, b[2, ], names(group), las = 2, tick = F)

legend(
  "topleft",
  legend = c("ESC-CRT survey II", "ESC-HF-LT", "SwedeHF"),
  bty = "n",
  fill = global_cols[c(7, 4, 1)],
  border = NA
)
```
